version: '3'

services:
   wallabag:
    image: wallabag/wallabag:latest
    container_name: wallabag
    restart: always
    networks:
      - web
      - intern
    environment:
      - SYMFONY__ENV__DATABASE_HOST=maria105master
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER= user 
      - SYMFONY__ENV__DATABASE_PASSWORD= ''
      - SYMFONY__ENV__DOMAIN_NAME=https://links.juliuslab.de
      - SYMFONY__ENV__FOSUSER_REGISTRATION=false
      - SYMFONY__ENV__FOSUSER_CONFIRMATION=false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wallabag.entrypoints=http"
      - "traefik.http.routers.wallabag.rule=Host(`DOMAIN`)"
      - "traefik.http.routers.wallabag.middlewares=https-redirect@file"
      - "traefik.http.routers.wallabag-sec.entrypoints=https"
      - "traefik.http.routers.wallabag-sec.middlewares=default-headers@file"
      - "traefik.http.routers.wallabag-sec.rule=Host(`DOMAIN`)"
      - "traefik.http.routers.wallabag-sec.tls=true"
      - "traefik.http.routers.wallabag-sec.tls.options=myTLSOptions@file"
      - "traefik.http.routers.wallabag-sec.tls.certresolver=le"
      - "traefik.http.services.wallabag.loadbalancer.server.port=80"
    volumes:
      - /srv/docker/data/wallabag/images:/var/www/wallabag/web/assets/images
      - /srv/docker/data/wallabag/data:/var/www/wallabag/data

networks:
  intern:
    external: true
  web:
    external: true