version: '3'

services:
 bitwarden:
  image: bitwardenrs/server:latest
  container_name: bitwarden
  restart: always
  networks:
   - intern
   - web
  ports:
   - 80
  environment:
   MYSQL_HOST: maria105master:3306
   MYSQL_PASSWORD: ''
   MYSQL_DATABASE: bitwarden
   MYSQL_USER: user
  labels:
   - "traefik.enable=true"
   - "traefik.http.routers.bitwarden.entrypoints=http"
   - "traefik.http.routers.bitwarden.rule=Host(`DOMAIN`)"
   - "traefik.http.routers.bitwarden.middlewares=https-redirect@file"
   - "traefik.http.routers.bitwarden-sec.entrypoints=https"
   - "traefik.http.routers.bitwarden-sec.middlewares=calcarddav,default-headers@file"
   - "traefik.http.routers.bitwarden-sec.rule=Host(`DOMAIN`)"
   - "traefik.http.routers.bitwarden-sec.tls=true"
   - "traefik.http.routers.bitwarden-sec.tls.options=myTLSOptions@file"
   - "traefik.http.routers.bitwarden-sec.tls.certresolver=le"
  volumes:
   - /srv/docker/data/bitwarden:/data
  external_links:
   - maria105master

networks:
  intern:
    external: true
  web:
    external: true

