version: '3'

services:
  heimdall:
    image: linuxserver/heimdall:latest
    container_name: heimdall
    restart: "always"
    networks:
      - intern
      - web
    ports:
      - 8085:80
    environment:
      - PGID=1000
      - PUID=1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heimdall.entrypoints=http"
      - "traefik.http.routers.heimdall.rule=Host(`DOMAIN`)"
      - "traefik.http.routers.heimdall.middlewares=https-redirect@file"
      - "traefik.http.routers.heimdall-sec.entrypoints=https"
      - "traefik.http.routers.heimdall-sec.rule=Host(`DOMAIN`)"
      - "traefik.http.routers.heimdall-sec.tls=true"
      - "traefik.http.routers.heimdall-sec.tls.certresolver=le"
      - "traefik.http.routers.heimdall-sec.service=heimdall"
      - "traefik.http.services.heimdall.loadbalancer.server.port=80"
    volumes:
      - /srv/docker/data/heimdall/config:/config

networks:
  intern:
    external: true
  web:
    external: true
